# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brandyn Schult
email: brandyn.schult@thalient.ai
name: &name "Brandyn Schult"
description: "A profile on Brandyn Schult and Thalient Cybernetics"
github_username: 
minimal_mistakes_skin: "dark"
search: true
masthead_title: " "

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /satori/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Brandyn Schult"
  avatar : "/assets/images/logo_head.webp"
  #bio    : "Merging scientific exploration and technological innovation with creative adaptation"
  bio  : "Transforming technology beyond function and towards understanding"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brandyn@thalient.ai"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bschult"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/thalient-ai/"
   
footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brandyn@thalient.ai"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bschult"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/thalient-ai/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/

analytics:
  provider: "custom"
