# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brandyn Schult
#title_separator: "|"
email: brandyn@thalient.ai
name: "Brandyn Schult"
description: "Thalient Cybernetics: A discipline to transform technology beyond function and towards understanding"
url: https://www.thalient.ai
minimal_mistakes_skin: "dirt"
search: true
masthead_title: "Thalient Cybernetics"
breadcrumbs: false
og_image: /assets/images/logo_blue_circle.webp
logo: /assets/images/logo_masthead.webp

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name   : "Brandyn Schult"
  avatar : "/assets/images/logo_head.webp"
  bio  : "Illegitimi non carborundum"
  location: "Orange County (CA)"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brandyn@thalient.ai"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:949-490-0614"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/thalient-ai/"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bschult"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brandyn@thalient.ai"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:949-490-0614"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/thalient-ai/"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/bschult"

# Collections
collections:
  cyber:
    output: true
    title: "Cybersecurity"
    permalink: /:collection/:path/
  syseng:
    output: true
    title: "Systems Engineering"
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _cyber
  - scope:
      path: ""
      type: cyber
    values:
      layout: single
      author_profile: false
  # _syseng
  - scope:
      path: ""
      type: syseng
    values:
      layout: single
      author_profile: false

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/

analytics:
  provider: "custom"

atom_feed:
  hide: false
